# Generated by Django 6.0.1 on 2026-05-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, default='', help_text='List any known allergies.'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_notes',
            field=models.TextField(blank=True, default='', help_text='Any existing conditions or notes for doctors.'),
        ),
    ]
