# Generated by Django 6.0.1 on 2026-05-16 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-rating', 'user__first_name']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(default='Mon,Tue,Wed,Thu,Fri', help_text='Comma-separated day abbreviations: Mon,Tue,Wed,Thu,Fri,Sat,Sun', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short professional biography shown to patients.'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Consultation fee in INR.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0, help_text='Years of professional experience.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/profiles/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating out of 5.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slot_duration_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Duration of each appointment slot in minutes.'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slot_end_time',
            field=models.TimeField(default='17:00', help_text='End time for appointment slots (HH:MM).'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slot_start_time',
            field=models.TimeField(default='09:00', help_text='Start time for appointment slots (HH:MM).'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Orthopedic', 'Orthopedic'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Gynecologist', 'Gynecologist'), ('ENT Specialist', 'ENT Specialist'), ('Ophthalmologist', 'Ophthalmologist'), ('Dentist', 'Dentist'), ('Urologist', 'Urologist'), ('Oncologist', 'Oncologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Pulmonologist', 'Pulmonologist'), ('Rheumatologist', 'Rheumatologist'), ('Nephrologist', 'Nephrologist'), ('Other', 'Other')], default='General Physician', max_length=100),
        ),
    ]
